version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: algakz/misis-admission-telegram-bot:latest
    restart: always
    env_file:
      - .env
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=tg-admission
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

